package dev.muon.raven_dnd_origins.power;

import dev.muon.raven_dnd_origins.RavenDndOrigins;
import dev.overgrown.apoli.power.PowerTypeRegistry;
import net.minecraft.resources.ResourceLocation;

public class ModPowers {
    public static final ResourceLocation INNATE_APTITUDE_BONUS = RavenDndOrigins.loc("innate_aptitude_bonus");
    public static final ResourceLocation ACTION_ON_LEVELUP = RavenDndOrigins.loc("action_on_levelup");
    public static final ResourceLocation TRADE_DISCOUNT = RavenDndOrigins.loc("trade_discount");
    public static final ResourceLocation MODIFY_THIRST_EXHAUSTION = RavenDndOrigins.loc("modify_thirst_exhaustion");
    public static final ResourceLocation CHARISMA = RavenDndOrigins.loc("charisma");
    public static final ResourceLocation HUNGER_IMMUNITY = RavenDndOrigins.loc("hunger_immunity");
    public static final ResourceLocation ELDRITCH_KNOWLEDGE = RavenDndOrigins.loc("eldritch_knowledge");
    public static final ResourceLocation ENCHANTING_KNOWLEDGE = RavenDndOrigins.loc("enchanting_knowledge");
    public static final ResourceLocation SHOW_REPAIR_TOOLTIP = RavenDndOrigins.loc("show_repair_tooltip");
    public static final ResourceLocation LEVELED_ATTRIBUTE = RavenDndOrigins.loc("leveled_attribute");
    public static final ResourceLocation MODIFY_STATUS_EFFECT_CATEGORY = RavenDndOrigins.loc("modify_status_effect_category");
    public static final ResourceLocation MODIFY_ENCHANTMENT_COST = RavenDndOrigins.loc("modify_enchantment_cost");
    public static final ResourceLocation INCREASE_ENCHANTING_LEVELS = RavenDndOrigins.loc("increase_enchanting_levels");
    public static final ResourceLocation PREVENT_CRITICAL_HIT = RavenDndOrigins.loc("prevent_critical_hit");
    public static final ResourceLocation MODIFY_CRITICAL_HIT = RavenDndOrigins.loc("modify_critical_hit");
    public static final ResourceLocation GOLD_DURABILITY = RavenDndOrigins.loc("gold_durability");
    public static final ResourceLocation LEVELED_RESOURCE = RavenDndOrigins.loc("leveled_resource");
    public static final ResourceLocation MODIFY_DAMAGE_TAKEN = RavenDndOrigins.loc("modify_damage_taken");
    public static final ResourceLocation HEAL_FROM_DAMAGE = RavenDndOrigins.loc("heal_from_damage");
    public static final ResourceLocation DEFLECT_PROJECTILE = RavenDndOrigins.loc("deflect_projectile");
    public static final ResourceLocation PLAYER_LEVEL = RavenDndOrigins.loc("player_level");
    public static final ResourceLocation SPELL_IMMUNITY = RavenDndOrigins.loc("spell_immunity");
    public static final ResourceLocation PREVENT_BLOCK_SLOWDOWN = RavenDndOrigins.loc("prevent_block_slowdown");
    public static final ResourceLocation PREVENT_REPAIR_PENALTY = RavenDndOrigins.loc("prevent_repair_penalty");
    public static final ResourceLocation ENHANCED_REPAIR = RavenDndOrigins.loc("enhanced_repair");
    public static final ResourceLocation ALLOWED_SPELLS = RavenDndOrigins.loc("allowed_spells");
    public static final ResourceLocation DIRECTIONAL_TELEPORT = RavenDndOrigins.loc("directional_teleport");
    public static final ResourceLocation SHAPESHIFT = RavenDndOrigins.loc("shapeshift");
    public static final ResourceLocation ACTION_ON_ATTACK = RavenDndOrigins.loc("action_on_attack");
    public static final ResourceLocation MODIFY_MAX_AIR_SUPPLY = RavenDndOrigins.loc("modify_max_air_supply");
    public static final ResourceLocation SUFFOCATION_IMMUNITY = RavenDndOrigins.loc("suffocation_immunity");
    public static final ResourceLocation THIRST_IMMUNITY = RavenDndOrigins.loc("thirst_immunity");
    public static final ResourceLocation EFFECT_CATEGORY_IMMUNITY = RavenDndOrigins.loc("effect_category_immunity");
    public static final ResourceLocation WALK_ON_POWDER_SNOW = RavenDndOrigins.loc("walk_on_powder_snow");
    public static final ResourceLocation JUMP_COOLDOWN = RavenDndOrigins.loc("jump_cooldown");
    public static final ResourceLocation MOBS_IGNORE = RavenDndOrigins.loc("mobs_ignore");
    public static final ResourceLocation INSPIRATION = RavenDndOrigins.loc("inspiration");
    public static final ResourceLocation ACTION_ON_SPELL_CAST = RavenDndOrigins.loc("action_on_spell_cast");
    public static final ResourceLocation ACTION_ON_SPELL_DAMAGE = RavenDndOrigins.loc("action_on_spell_damage");
    public static final ResourceLocation RECAST_SPELL = RavenDndOrigins.loc("recast_spell");
    public static final ResourceLocation ARCANE_WARD_PREVENT_DEATH = RavenDndOrigins.loc("arcane_ward_prevent_death");
    public static final ResourceLocation MODIFY_PROJECTILE_VELOCITY = RavenDndOrigins.loc("modify_projectile_velocity");
    public static final ResourceLocation MODIFY_PROJECTILE_ACCURACY = RavenDndOrigins.loc("modify_projectile_accuracy");
    public static final ResourceLocation MODIFY_PIERCE_LEVEL = RavenDndOrigins.loc("modify_pierce_level");
    public static final ResourceLocation MULTISHOT = RavenDndOrigins.loc("multishot");
    public static final ResourceLocation MOMENTUM = RavenDndOrigins.loc("momentum");
    public static final ResourceLocation MODIFY_BREWED_POTION = RavenDndOrigins.loc("modify_brewed_potion");
    public static final ResourceLocation PREVENT_WING_BOOST = RavenDndOrigins.loc("prevent_wing_boost");
    public static final ResourceLocation BYPASS_ARMOR_WEIGHT = RavenDndOrigins.loc("bypass_armor_weight");

    public static void register() {
        PowerTypeRegistry.register(INNATE_APTITUDE_BONUS, new InnateAptitudeBonusPower());
        PowerTypeRegistry.register(ACTION_ON_LEVELUP, new ActionOnLevelupPower());
        PowerTypeRegistry.register(TRADE_DISCOUNT, new TradeDiscountPower());
        PowerTypeRegistry.register(MODIFY_THIRST_EXHAUSTION, new ModifyThirstExhaustionPower());
        PowerTypeRegistry.register(CHARISMA, new CharismaPower());
        PowerTypeRegistry.register(HUNGER_IMMUNITY, new HungerImmunityPower());
        PowerTypeRegistry.register(ELDRITCH_KNOWLEDGE, new EldritchKnowledgePower());
        PowerTypeRegistry.register(ENCHANTING_KNOWLEDGE, new EnchantingKnowledgePower());
        PowerTypeRegistry.register(SHOW_REPAIR_TOOLTIP, new ShowRepairTooltipPower());
        PowerTypeRegistry.register(LEVELED_ATTRIBUTE, new LeveledAttributePower());
        PowerTypeRegistry.register(MODIFY_STATUS_EFFECT_CATEGORY, ModifyStatusEffectCategoryPower.INSTANCE);
        PowerTypeRegistry.register(MODIFY_ENCHANTMENT_COST, new ModifyEnchantmentCostPower());
        PowerTypeRegistry.register(INCREASE_ENCHANTING_LEVELS, new IncreaseEnchantingLevelsPower());
        PowerTypeRegistry.register(PREVENT_CRITICAL_HIT, new PreventCriticalHitPower());
        PowerTypeRegistry.register(MODIFY_CRITICAL_HIT, new ModifyCriticalHitPower());
        PowerTypeRegistry.register(GOLD_DURABILITY, new GoldDurabilityPower());
        PowerTypeRegistry.register(LEVELED_RESOURCE, new LeveledResourcePower());
        PowerTypeRegistry.register(MODIFY_DAMAGE_TAKEN, new ModifyDamageTakenDirectPower());
        PowerTypeRegistry.register(HEAL_FROM_DAMAGE, new HealFromDamagePower());
        PowerTypeRegistry.register(DEFLECT_PROJECTILE, new DeflectProjectilePower());
        PowerTypeRegistry.register(PLAYER_LEVEL, new PlayerLevelPower());
        PowerTypeRegistry.register(SPELL_IMMUNITY, new SpellImmunityPower());
        PowerTypeRegistry.register(PREVENT_BLOCK_SLOWDOWN, new PreventBlockSlowdownPower());
        PowerTypeRegistry.register(PREVENT_REPAIR_PENALTY, new PreventRepairPenaltyPower());
        PowerTypeRegistry.register(ENHANCED_REPAIR, new EnhancedRepairPower());
        PowerTypeRegistry.register(ALLOWED_SPELLS, new AllowedSpellsPower());
        PowerTypeRegistry.register(DIRECTIONAL_TELEPORT, new DirectionalTeleportPower());
        PowerTypeRegistry.register(SHAPESHIFT, new ShapeshiftPower());
        PowerTypeRegistry.register(ACTION_ON_ATTACK, new ActionOnAttackPower());
        PowerTypeRegistry.register(MODIFY_MAX_AIR_SUPPLY, new ModifyMaxAirSupplyPower());
        PowerTypeRegistry.register(SUFFOCATION_IMMUNITY, new SuffocationImmunityPower());
        PowerTypeRegistry.register(THIRST_IMMUNITY, new ThirstImmunityPower());
        PowerTypeRegistry.register(EFFECT_CATEGORY_IMMUNITY, new EffectCategoryImmunityPower());
        PowerTypeRegistry.register(WALK_ON_POWDER_SNOW, new WalkOnPowderSnowPower());
        PowerTypeRegistry.register(JUMP_COOLDOWN, new JumpCooldownPower());
        PowerTypeRegistry.register(MOBS_IGNORE, new MobsIgnorePower());
        PowerTypeRegistry.register(INSPIRATION, new InspirationPower());
        PowerTypeRegistry.register(ACTION_ON_SPELL_CAST, new ActionOnSpellCastPower());
        PowerTypeRegistry.register(ACTION_ON_SPELL_DAMAGE, new ActionOnSpellDamagePower());
        PowerTypeRegistry.register(RECAST_SPELL, new RecastSpellPower());
        PowerTypeRegistry.register(ARCANE_WARD_PREVENT_DEATH, new ArcaneWardPreventDeathPower());
        PowerTypeRegistry.register(MODIFY_PROJECTILE_VELOCITY, new ModifyProjectileVelocityPower());
        PowerTypeRegistry.register(MODIFY_PROJECTILE_ACCURACY, new ModifyProjectileAccuracyPower());
        PowerTypeRegistry.register(MODIFY_PIERCE_LEVEL, new ModifyPierceLevelPower());
        PowerTypeRegistry.register(MULTISHOT, new MultishotPower());
        PowerTypeRegistry.register(MOMENTUM, new MomentumPower());
        PowerTypeRegistry.register(MODIFY_BREWED_POTION, new ModifyBrewedPotionPower());
        PowerTypeRegistry.register(PREVENT_WING_BOOST, new PreventWingBoostPower());
        PowerTypeRegistry.register(BYPASS_ARMOR_WEIGHT, new BypassArmorWeightPower());
    }
}
